# vim: set ft=ansible
- hosts: oranges
  remote_user: root
  vars:
    max_cpu_freq: 1000000
    max_ram_freq: 500mhz
    max_cpu_cores: 4
    wifi_passwd: tent_controller_wifi
  tasks:

    - name: set hostname
      hostname: name={{ inventory_hostname }}
      tags:
        - base

    - name: update system
      apt:
        update_cache: yes
        upgrade: yes
      tags:
        - upgrade
        
    - name: install packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - vim
        - tmux
        - bridge-utils
        - hostapd
        - firmware-atheros
        - firmware-realtek
      tags:
        - base

    - name: turn gpu off
      command: /usr/bin/h3consumption -g off
      tags:
        - base

    - name: lower mem speed
      command: /usr/bin/h3consumption -d {{ max_ram_freq }}
      tags:
        - base

    - name: set max cpu cores
      command: /usr/bin/h3consumption -c {{ max_cpu_cores }}
      tags:
        - base

    - name: set max cpu speed
      template:
        src: etc/default/cpufrequtils
        dest: /etc/default/cpufrequtils
      tags:
        - base

    - name: set hostapd defaults
      template:
        src: etc/default/hostapd
        dest: /etc/default/hostapd
      tags:
        - ap

    - name: create directory for ansible custom facts
      file: state=directory recurse=yes path=/etc/ansible/facts.d
      tags:
        - ap

    - name: install wpa psk fact
      template:
        src: etc/ansible/facts.d/wpa_psk.fact
        dest: /etc/ansible/facts.d/wpa_psk.fact
        mode: 0755
      register: _wpa_fact
      tags:
        - ap

    - name: reread facts
      setup: filter=ansible_local
      when: _wpa_fact|changed
      tags:
        - ap

    - name: set hostapd config
      template:
        src: etc/hostapd.conf
        dest: /etc/hostapd.conf
      tags:
        - ap

    - name: install interfaces
      template:
        src: etc/network/interfaces
        dest: /etc/network/interfaces
      register: _networking
      tags:
        - ap

    - name: networking restart
      service:
        name: networking
        state: restarted
      tags:
        - ap
      when: _networking|changed

    - name: restart hostapd
      service:
        name: hostapd.service
        state: restarted
        enabled: true
      tags:
        - ap

    - name: sync filesystem
      command: /bin/sync
      tags:
        - base
        - ap

